didn't compile due to missing Main function
I forgot to include the main function when trying to optimize the code and it didn't compile which resulted in the following error:

arm-linux-gcc -static -o encodeOpt.exe encodeOpt.s
/opt/arm/4.3.2/bin/../arm-none-linux-gnueabi/libc/armv4t/usr/lib/crt1.o: In function `_start':
init.c:(.text+0x30): undefined reference to `main'
collect2: ld returned 1 exit status

I added a main function and I am going to test it again